//Importing metadata and fonts
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


/*Font variables*/
//defines geistSansn function which returns a font object from the Geist font, but only the latin portion.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

//defines geistMono function which returns a font object from the Geist_Mono font, but only the latin portion.
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


/*Metadata variable*/
//We are creating a metadata variable that will be used to set the title and description of the page.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


/*Defining the deault html layout of - RootLayout*/
/*Next.js automatically takes whatever you return from the page and passes it as the children prop to the RootLayout.*/
export default function RootLayout({
  children, // name of our prop that will contain the children of the layout
}: Readonly<{ //Sets the prop as readonly 
  children: React.ReactNode; //Sets childrens type to be of a react type
//Sets language to english, set our fonts that we defined eariler and uses the tailwind untility class antialiased on the text.
}>) {
  return (
    <html lang="en"> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
